### ISSUE TITLE
Add LD-Patch generator

### ISSUE THREAD

**Issue by sandhawke** [linkeddata/gold#18] opened 2014-09-17 17:05 UTC
Implement code to generate an LD-Patch from two RDF graphs.   (that is, it's "diff" for RDF)   We also would like this in JavaScript, but maybe GopherJS could be used to generate that from this golang version.

**Comment by deiu** [comment] 2015-04-17 18:26
Duplicate of #16

**Closed by deiu** 2015-04-17 18:26 UTC
Labels: duplicate
